// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/capture-preview-redesign/ChooseBestPortrait.tsx": () => import("../components/mockups/capture-preview-redesign/ChooseBestPortrait.tsx"),
  "./components/mockups/capture-preview-redesign/CompareTwoCaptures.tsx": () => import("../components/mockups/capture-preview-redesign/CompareTwoCaptures.tsx"),
  "./components/mockups/capture-preview-redesign/Current.tsx": () => import("../components/mockups/capture-preview-redesign/Current.tsx"),
  "./components/mockups/capture-preview-redesign/DesktopWithChanges.tsx": () => import("../components/mockups/capture-preview-redesign/DesktopWithChanges.tsx"),
  "./components/mockups/capture-preview-redesign/LatestFilmstrip.tsx": () => import("../components/mockups/capture-preview-redesign/LatestFilmstrip.tsx"),
  "./components/mockups/capture-preview-redesign/OriginalVsEdited.tsx": () => import("../components/mockups/capture-preview-redesign/OriginalVsEdited.tsx"),
  "./components/mockups/capture-preview-redesign/ReframeEditor.tsx": () => import("../components/mockups/capture-preview-redesign/ReframeEditor.tsx"),
  "./components/mockups/project-action-sidebar/ProjectSidebar.tsx": () => import("../components/mockups/project-action-sidebar/ProjectSidebar.tsx"),
  "./components/mockups/project-view-classes/Current.tsx": () => import("../components/mockups/project-view-classes/Current.tsx")

};
