export const deliveryLocales = ["fr", "en", "sv", "es"] as const;
export type DeliveryLocale = (typeof deliveryLocales)[number];

const messages = {
  fr: {
    loading: "Chargement de la galerie…", unavailable: "Livraison indisponible", unavailableText: "Cette galerie est introuvable ou n’est plus active.",
    privateGallery: "Votre galerie privée", accessText: "Saisissez le code de votre carte photo pour voir les aperçus et commander des photos numériques.", accessCode: "Code d’accès", openGallery: "Ouvrir la galerie", invalidCode: "Ce code d’accès n’est pas valide.", openError: "Impossible d’ouvrir la galerie. Veuillez réessayer.", contact: "Si vous ne trouvez pas votre code, contactez le studio photo.", studio: "Studio",
    checkout: "Commande", back: "Retour à la galerie", empty: "Votre panier est vide", returnGallery: "Retour à la galerie", basket: "Votre panier", deliveryPayment: "Livraison et paiement", name: "Votre nom *", email: "Adresse e-mail", deliveryMethod: "Mode de livraison *", paymentMethod: "Mode de paiement *", address: "Adresse de livraison *", total: "Total", placeOrder: "Passer la commande", remove: "Supprimer", qty: "Qté :", digitalDelivery: "Livraison numérique", payStripe: "Carte avec Stripe", payEstablishment: "Payer au studio", payBank: "Virement bancaire", checkoutUnavailable: "Ces produits n’ont pas de mode de paiement et de livraison commun disponible. Supprimez un produit ou réessayez lorsque le paiement par carte sera disponible.", orderError: "Une erreur est survenue lors de la commande. Veuillez réessayer.",
    anotherCode: "Utiliser un autre code", privateDelivery: "Livraison privée", preview: "aperçu", previews: "aperçus", chooseProduct: "Choisissez un produit", quantity: "Quantité :", perPhoto: "1 unité par photo sélectionnée", selectOne: "Sélectionnez 1 photo", perPack: "photo(s) par lot", cannotCombine: "Ce produit ne peut pas être acheté avec les articles actuels : les modes de paiement/livraison ou les devises diffèrent. Terminez votre commande ou videz votre panier.", added: "a été ajouté à votre panier.", accessAvailable: "L’accès aux photos est disponible, mais ce studio n’a pas encore configuré d’offre active.", notReady: "Les photos ne sont pas encore prêtes", checkLater: "Veuillez revenir plus tard ou contacter le studio.", refresh: "Actualiser", photoPreview: "Aperçu photo", purchased: "Acheté", success: "Commande réussie", downloadsReady: "Vos photos achetées sont disponibles au téléchargement ci-dessous.", processing: "Votre commande a été reçue et sera bientôt traitée.", download: "Télécharger", selected: "photo(s) sélectionnée(s)", current: "Sélection actuelle", item: "article(s) dans le panier", basketTotal: "Total du panier", add: "Ajouter au panier", card: "Langue",
    paymentReceived: "Paiement reçu. Nous confirmons votre commande et préparons vos téléchargements.", paidReady: "Paiement confirmé. Vos photos payées sont prêtes à télécharger.", paidPreparing: "Paiement confirmé. Nous préparons votre commande.", orderReceived: "Commande reçue.", paymentFallback: "Le studio confirmera le paiement avant de traiter la commande."
  },
  en: {
    loading: "Loading gallery…", unavailable: "Delivery unavailable", unavailableText: "This gallery could not be found or is no longer active.", privateGallery: "Your private gallery", accessText: "Enter the access code from your photo card to view previews and order digital photos.", accessCode: "Access code", openGallery: "Open gallery", invalidCode: "That access code is not valid.", openError: "The gallery could not be opened. Please try again.", contact: "If you cannot find your code, please contact the photography studio.", studio: "Studio", checkout: "Checkout", back: "Back to Gallery", empty: "Your basket is empty", returnGallery: "Return to Gallery", basket: "Your Basket", deliveryPayment: "Delivery & Payment", name: "Your Name *", email: "Email Address", deliveryMethod: "Delivery Method *", paymentMethod: "Payment Method *", address: "Shipping Address *", total: "Total", placeOrder: "Place Order", remove: "Remove", qty: "Qty:", digitalDelivery: "Digital Delivery", payStripe: "Card with Stripe", payEstablishment: "Pay at establishment", payBank: "Bank transfer", checkoutUnavailable: "These products do not currently share an available payment and delivery method. Remove one product or try again when card payments are available.", orderError: "There was an error placing your order. Please try again.", anotherCode: "Use another code", privateDelivery: "Private delivery", preview: "Preview", previews: "previews", chooseProduct: "Choose a product", quantity: "Quantity:", perPhoto: "1 unit per selected photo", selectOne: "Select 1 photo", perPack: "photo(s) per pack", cannotCombine: "This product cannot be purchased together with items currently in your basket because they require different payment/delivery methods or use different currencies. Please complete your current order first, or clear your basket.", added: "added to your basket.", accessAvailable: "Private photo access is available, but this studio has not configured an active offer yet.", notReady: "Photos are not ready yet", checkLater: "Please check again later or contact the studio.", refresh: "Refresh", photoPreview: "Photo preview", purchased: "Purchased", success: "Order Successful", downloadsReady: "Your purchased photos are available to download below.", processing: "Your order has been received and will be processed soon.", download: "Download", selected: "photo(s) selected", current: "Current selection", item: "item(s) in basket", basketTotal: "Basket Total", add: "Add to Basket", card: "Language", paymentReceived: "Payment received. We are confirming your order and preparing your downloads.", paidReady: "Payment confirmed. Your paid photos are ready to download.", paidPreparing: "Payment confirmed. We are preparing your order.", orderReceived: "Order received.", paymentFallback: "The studio will confirm payment before processing the order."
  },
  sv: {
    loading: "Laddar galleri…", unavailable: "Leverans inte tillgänglig", unavailableText: "Galleriet kunde inte hittas eller är inte längre aktivt.", privateGallery: "Ditt privata galleri", accessText: "Ange åtkomstkoden från ditt fotokort för att se förhandsvisningar och beställa digitala foton.", accessCode: "Åtkomstkod", openGallery: "Öppna galleri", invalidCode: "Åtkomstkoden är ogiltig.", openError: "Galleriet kunde inte öppnas. Försök igen.", contact: "Kontakta fotostudion om du inte hittar koden.", studio: "Studio", checkout: "Kassa", back: "Tillbaka till galleri", empty: "Din varukorg är tom", returnGallery: "Tillbaka till galleri", basket: "Din varukorg", deliveryPayment: "Leverans och betalning", name: "Ditt namn *", email: "E-postadress", deliveryMethod: "Leveranssätt *", paymentMethod: "Betalsätt *", address: "Leveransadress *", total: "Totalt", placeOrder: "Lägg beställning", remove: "Ta bort", qty: "Antal:", digitalDelivery: "Digital leverans", payStripe: "Kort med Stripe", payEstablishment: "Betala på plats", payBank: "Banköverföring", checkoutUnavailable: "Produkterna saknar ett gemensamt tillgängligt betalnings- och leveranssätt.", orderError: "Ett fel uppstod när beställningen lades. Försök igen.", anotherCode: "Använd en annan kod", privateDelivery: "Privat leverans", preview: "Förhandsvisning", previews: "förhandsvisningar", chooseProduct: "Välj en produkt", quantity: "Antal:", perPhoto: "1 enhet per valt foto", selectOne: "Välj 1 foto", perPack: "foto per paket", cannotCombine: "Produkten kan inte köpas med varukorgens artiklar eftersom betalning, leverans eller valuta skiljer sig.", added: "lades till i varukorgen.", accessAvailable: "Privat fotoåtkomst är tillgänglig, men studion har inget aktivt erbjudande.", notReady: "Foton är inte redo ännu", checkLater: "Försök igen senare eller kontakta studion.", refresh: "Uppdatera", photoPreview: "Fotoförhandsvisning", purchased: "Köpt", success: "Beställning lyckades", downloadsReady: "Dina köpta foton kan laddas ner nedan.", processing: "Din beställning har mottagits och behandlas snart.", download: "Ladda ner", selected: "valt foto", current: "Aktuellt urval", item: "artikel i varukorgen", basketTotal: "Varukorg totalt", add: "Lägg i varukorg", card: "Språk", paymentReceived: "Betalning mottagen. Vi bekräftar din beställning och förbereder dina nedladdningar.", paidReady: "Betalning bekräftad. Dina betalda foton kan laddas ner.", paidPreparing: "Betalning bekräftad. Vi förbereder din beställning.", orderReceived: "Beställning mottagen.", paymentFallback: "Studion bekräftar betalningen innan beställningen behandlas."
  },
  es: {
    loading: "Cargando galería…", unavailable: "Entrega no disponible", unavailableText: "No se encontró esta galería o ya no está activa.", privateGallery: "Tu galería privada", accessText: "Introduce el código de tu tarjeta de fotos para ver las vistas previas y pedir fotos digitales.", accessCode: "Código de acceso", openGallery: "Abrir galería", invalidCode: "El código de acceso no es válido.", openError: "No se pudo abrir la galería. Inténtalo de nuevo.", contact: "Si no encuentras el código, contacta con el estudio fotográfico.", studio: "Estudio", checkout: "Finalizar pedido", back: "Volver a la galería", empty: "Tu cesta está vacía", returnGallery: "Volver a la galería", basket: "Tu cesta", deliveryPayment: "Entrega y pago", name: "Tu nombre *", email: "Dirección de correo", deliveryMethod: "Método de entrega *", paymentMethod: "Método de pago *", address: "Dirección de envío *", total: "Total", placeOrder: "Realizar pedido", remove: "Eliminar", qty: "Cant.:", digitalDelivery: "Entrega digital", payStripe: "Tarjeta con Stripe", payEstablishment: "Pagar en el estudio", payBank: "Transferencia bancaria", checkoutUnavailable: "Estos productos no comparten un método de pago y entrega disponible. Elimina un producto o inténtalo cuando el pago con tarjeta esté disponible.", orderError: "Se produjo un error al realizar el pedido. Inténtalo de nuevo.", anotherCode: "Usar otro código", privateDelivery: "Entrega privada", preview: "Vista previa", previews: "vistas previas", chooseProduct: "Elige un producto", quantity: "Cantidad:", perPhoto: "1 unidad por foto seleccionada", selectOne: "Selecciona 1 foto", perPack: "foto(s) por paquete", cannotCombine: "Este producto no se puede comprar con los artículos actuales porque requieren métodos de pago/entrega o monedas diferentes. Completa el pedido actual o vacía la cesta.", added: "se añadió a tu cesta.", accessAvailable: "El acceso privado está disponible, pero el estudio aún no ha configurado una oferta activa.", notReady: "Las fotos aún no están listas", checkLater: "Vuelve a intentarlo más tarde o contacta con el estudio.", refresh: "Actualizar", photoPreview: "Vista previa de foto", purchased: "Comprada", success: "Pedido realizado", downloadsReady: "Tus fotos compradas están disponibles para descargar abajo.", processing: "Hemos recibido tu pedido y se procesará pronto.", download: "Descargar", selected: "foto(s) seleccionada(s)", current: "Selección actual", item: "artículo(s) en la cesta", basketTotal: "Total de la cesta", add: "Añadir a la cesta", card: "Idioma", paymentReceived: "Pago recibido. Confirmaremos tu pedido y prepararemos tus descargas.", paidReady: "Pago confirmado. Tus fotos pagadas están listas para descargar.", paidPreparing: "Pago confirmado. Estamos preparando tu pedido.", orderReceived: "Pedido recibido.", paymentFallback: "El estudio confirmará el pago antes de procesar el pedido."
  }
} as const;

export type DeliveryMessageKey = keyof typeof messages.en;
export function getStoredDeliveryLocale(): DeliveryLocale {
  const stored = typeof localStorage !== "undefined" ? localStorage.getItem("delivery-locale") : null;
  if (stored && deliveryLocales.includes(stored as DeliveryLocale)) return stored as DeliveryLocale;
  const browser = typeof navigator !== "undefined" ? navigator.language.slice(0, 2) : "";
  return deliveryLocales.includes(browser as DeliveryLocale) ? browser as DeliveryLocale : "fr";
}
export function translate(locale: DeliveryLocale, key: DeliveryMessageKey): string { return messages[locale][key] || messages.en[key]; }
export function formatDeliveryPrice(amount: number, currency: string, locale: DeliveryLocale) {
  try {
    return new Intl.NumberFormat(locale, { style: "currency", currency: currency.toUpperCase() }).format(amount / 100);
  } catch {
    return `${(amount / 100).toFixed(2)} ${currency.toUpperCase()}`;
  }
}